[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://xyzcompany.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlc3QiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTYxNjE1MjU1MCwiZXhwIjoxOTMxNzI4NTUwfQ.Dr_pYQpJXlI-WD-Mex3KAJDEjwMm8ckjRFcHYhYnTYM"
  VITE_APP_TITLE = "CampusPandit - Smart Learning Platform"
  VITE_APP_VERSION = "1.0.0"
  VITE_APP_ENVIRONMENT = "production"
  VITE_ENABLE_GAMING = "true"
  VITE_ENABLE_OFFLINE_MODE = "true"
  VITE_ENABLE_PWA_PROMPTS = "true"
  VITE_ENABLE_COMPETITIVE_EXAMS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200