"""
AI Coaching Models
Database models for AI-based coaching and weak area management
"""

from sqlalchemy import Column, String, Integer, Float, Boolean, DateTime, Enum as SQLEnum, JSON, Text, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
import uuid
import enum

from app.core.database import Base


# =====================================================
# ENUMS
# =====================================================

class Subject(str, enum.Enum):
    """Subject enumeration"""
    PHYSICS = "physics"
    MATHEMATICS = "mathematics"
    CHEMISTRY = "chemistry"
    BIOLOGY = "biology"
    COMPUTER_SCIENCE = "computer_science"
    ENGLISH = "english"
    OTHER = "other"


class WeaknessSeverity(str, enum.Enum):
    """Weakness severity levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class WeakAreaStatus(str, enum.Enum):
    """Weak area status"""
    ACTIVE = "active"
    IMPROVING = "improving"
    RESOLVED = "resolved"
    IGNORED = "ignored"


class IdentifiedFrom(str, enum.Enum):
    """Source of weak area identification"""
    FLASHCARD_ACCURACY = "flashcard_accuracy"
    TUTOR_SESSION = "tutor_session"
    MOCK_TEST = "mock_test"
    CHAPTER_PROGRESS = "chapter_progress"
    SELF_ASSESSMENT = "self_assessment"
    AI_ANALYSIS = "ai_analysis"


class SessionType(str, enum.Enum):
    """Coaching session types"""
    DAILY = "daily"
    WEEKLY = "weekly"
    EMERGENCY = "emergency"
    MILESTONE = "milestone"
    EXAM_PREP = "exam_prep"


class RepetitionStatus(str, enum.Enum):
    """Repetition schedule status"""
    SCHEDULED = "scheduled"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    SKIPPED = "skipped"
    RESCHEDULED = "rescheduled"


class ContentType(str, enum.Enum):
    """Content type for repetitions"""
    FLASHCARDS = "flashcards"
    PROBLEMS = "problems"
    THEORY = "theory"
    VIDEO = "video"
    TUTOR_SESSION = "tutor_session"
    MIXED = "mixed"


class RecommendationStatus(str, enum.Enum):
    """Recommendation status"""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    DISMISSED = "dismissed"


class RecommendationPriority(str, enum.Enum):
    """Recommendation priority levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class PeriodType(str, enum.Enum):
    """Analytics period types"""
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    ALL_TIME = "all_time"


# =====================================================
# MODELS
# =====================================================

class StudentWeakArea(Base):
    """Student weak areas identified by AI"""
    __tablename__ = "student_weak_areas"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    student_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    subject = Column(SQLEnum(Subject), nullable=False)
    topic = Column(String(255), nullable=False)
    subtopic = Column(String(255))
    chapter_id = Column(UUID(as_uuid=True))
    resource_id = Column(UUID(as_uuid=True))

    # Severity and priority
    weakness_severity = Column(SQLEnum(WeaknessSeverity), nullable=False)
    priority = Column(Integer, nullable=False)  # 1-10, higher = more urgent

    # Identification info
    identified_from = Column(SQLEnum(IdentifiedFrom), nullable=False)
    identification_reason = Column(Text)

    # Performance metrics
    current_accuracy_percentage = Column(Float)
    attempts_count = Column(Integer, default=0)
    failures_count = Column(Integer, default=0)

    # Status and progress
    status = Column(SQLEnum(WeakAreaStatus), nullable=False, default=WeakAreaStatus.ACTIVE)
    times_repeated = Column(Integer, default=0)
    target_repetitions = Column(Integer, default=5)
    initial_accuracy = Column(Float)
    current_improvement_percentage = Column(Float)
    target_accuracy_percentage = Column(Float, default=80.0)

    # Next review
    next_review_date = Column(DateTime(timezone=True))

    # Notes and recommendations
    ai_recommendations = Column(JSON)  # Array of recommendation strings
    tutor_notes = Column(Text)
    student_notes = Column(Text)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    def __repr__(self):
        return f"<WeakArea {self.subject}:{self.topic} - {self.weakness_severity}>"


class AICoachingSession(Base):
    """Daily/weekly coaching sessions generated by AI"""
    __tablename__ = "ai_coaching_sessions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    student_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Session info
    session_type = Column(SQLEnum(SessionType), nullable=False)
    session_focus = Column(JSON)  # Array of focus areas

    # Weak area summary
    weak_areas_identified = Column(Integer, default=0)
    weak_areas_improving = Column(Integer, default=0)
    weak_areas_resolved = Column(Integer, default=0)
    new_weak_areas_found = Column(Integer, default=0)

    # Performance summary
    overall_accuracy = Column(Float)
    study_hours_this_week = Column(Float)
    topics_studied_count = Column(Integer)
    flashcards_reviewed = Column(Integer)
    problems_solved = Column(Integer)

    # AI-generated content
    recommendations = Column(JSON)  # Structured recommendations object
    priority_actions = Column(JSON)  # Array of high-priority action items
    suggested_study_plan = Column(Text)
    motivational_message = Column(Text)

    # Interaction
    student_viewed = Column(Boolean, default=False)
    viewed_at = Column(DateTime(timezone=True))

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    def __repr__(self):
        return f"<CoachingSession {self.session_type} - {self.created_at}>"


class RepetitionSchedule(Base):
    """Spaced repetition schedule for weak areas"""
    __tablename__ = "repetition_schedule"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    student_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    weak_area_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Schedule info
    repetition_number = Column(Integer, nullable=False)  # 1, 2, 3, etc.
    scheduled_date = Column(DateTime(timezone=True), nullable=False, index=True)
    scheduled_time_slot = Column(String(50))  # e.g., "morning", "afternoon", "evening"

    # Content to review
    content_type = Column(SQLEnum(ContentType), nullable=False)
    flashcard_set_id = Column(UUID(as_uuid=True))
    problems_to_solve = Column(JSON)  # Array of problem IDs
    chapters_to_review = Column(JSON)  # Array of chapter IDs
    estimated_duration_minutes = Column(Integer)

    # Status and completion
    status = Column(SQLEnum(RepetitionStatus), nullable=False, default=RepetitionStatus.SCHEDULED)
    completed_at = Column(DateTime(timezone=True))
    accuracy_achieved = Column(Float)
    problems_attempted = Column(Integer)
    problems_solved = Column(Integer)
    notes = Column(Text)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    def __repr__(self):
        return f"<Repetition #{self.repetition_number} - {self.scheduled_date}>"


class StudentPerformanceAnalytics(Base):
    """Aggregated performance analytics"""
    __tablename__ = "student_performance_analytics"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    student_id = Column(UUID(as_uuid=True), nullable=False, index=True)

    # Period info
    analysis_date = Column(DateTime(timezone=True), nullable=False, index=True)
    period_type = Column(SQLEnum(PeriodType), nullable=False)
    period_start = Column(DateTime(timezone=True), nullable=False)
    period_end = Column(DateTime(timezone=True), nullable=False)

    # Activity metrics
    total_study_hours = Column(Float)
    total_flashcards_reviewed = Column(Integer)
    total_problems_solved = Column(Integer)
    total_tutor_sessions = Column(Integer)
    average_session_rating = Column(Float)

    # Subject-wise accuracy
    physics_accuracy = Column(Float)
    mathematics_accuracy = Column(Float)
    chemistry_accuracy = Column(Float)
    biology_accuracy = Column(Float)

    # Weak area metrics
    active_weak_areas = Column(Integer)
    resolved_weak_areas_this_period = Column(Integer)
    new_weak_areas_this_period = Column(Integer)

    # Performance indicators
    overall_improvement_percentage = Column(Float)
    study_consistency_score = Column(Float)  # 0-100
    target_achievement_percentage = Column(Float)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    def __repr__(self):
        return f"<Analytics {self.period_type} - {self.analysis_date}>"


class CoachingRecommendation(Base):
    """AI-generated coaching recommendations"""
    __tablename__ = "coaching_recommendations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    student_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    weak_area_id = Column(UUID(as_uuid=True), index=True)
    coaching_session_id = Column(UUID(as_uuid=True), index=True)

    # Recommendation details
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    action_items = Column(JSON)  # Array of specific action items

    # Priority and categorization
    priority = Column(SQLEnum(RecommendationPriority), nullable=False)
    category = Column(String(100))  # e.g., "study_technique", "time_management", "content_review"
    estimated_time_minutes = Column(Integer)

    # Status and progress
    status = Column(SQLEnum(RecommendationStatus), nullable=False, default=RecommendationStatus.PENDING)
    completion_percentage = Column(Integer, default=0)

    # Tracking
    started_at = Column(DateTime(timezone=True))
    completed_at = Column(DateTime(timezone=True))
    student_notes = Column(Text)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    def __repr__(self):
        return f"<Recommendation {self.title} - {self.priority}>"


class ImprovementMilestone(Base):
    """Track and celebrate student improvements"""
    __tablename__ = "improvement_milestones"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    student_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    weak_area_id = Column(UUID(as_uuid=True), index=True)

    # Milestone info
    milestone_type = Column(String(100), nullable=False)  # e.g., "weak_area_resolved", "accuracy_improved", "consistency_achieved"
    title = Column(String(255), nullable=False)
    description = Column(Text)

    # Metrics
    previous_value = Column(Float)
    new_value = Column(Float)
    improvement_percentage = Column(Float)

    # Achievement
    achievement_date = Column(DateTime(timezone=True), nullable=False)
    celebration_message = Column(Text)
    student_viewed = Column(Boolean, default=False)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    def __repr__(self):
        return f"<Milestone {self.milestone_type} - {self.achievement_date}>"


class AICoachingConfig(Base):
    """Student-specific coaching configuration"""
    __tablename__ = "ai_coaching_config"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    student_id = Column(UUID(as_uuid=True), nullable=False, unique=True, index=True)

    # Schedule preferences
    daily_coaching_time = Column(String(10))  # e.g., "09:00", "18:00"
    weekly_summary_day = Column(String(10))  # e.g., "sunday", "monday"

    # Thresholds
    weak_area_threshold_percentage = Column(Float, default=70.0)
    critical_threshold_percentage = Column(Float, default=50.0)
    mastery_threshold_percentage = Column(Float, default=80.0)

    # Repetition settings
    default_repetition_count = Column(Integer, default=5)
    days_between_repetitions = Column(Integer, default=3)  # For spaced repetition
    auto_schedule_repetitions = Column(Boolean, default=True)

    # Notification preferences
    notifications_enabled = Column(Boolean, default=True)
    notification_channels = Column(JSON)  # ["email", "push", "sms"]
    receive_motivation_messages = Column(Boolean, default=True)

    # Personalization
    coaching_tone = Column(String(50), default="encouraging")  # encouraging, professional, casual
    focus_areas = Column(JSON)  # Array of subjects to focus on
    learning_style_preference = Column(String(50))  # visual, auditory, kinesthetic, reading

    # Goals
    target_exam = Column(String(100))
    target_exam_date = Column(DateTime(timezone=True))
    daily_study_goal_hours = Column(Float, default=2.0)

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    def __repr__(self):
        return f"<CoachingConfig for student {self.student_id}>"
